apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gowsdl
  description: WSDL2Go code generation as well as its SOAP proxy
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
